# CombatTime - время без ударов до снятия состояния боя в секундах
CombatTime: 20

#Message - сообщение игроку, когда он пытается использовать запрещённые команды, %sec% - время до конца боя
Message: §5Вы не можете использовать команды в бою, осталось %sec%с.

# ListType - тип списка команд, "ALL" - в бою запрещены все команды, "BLACKLIST" - запрещены только указанные, "WHITELIST" - разрешены только указанные
ListType: BLACKLIST

# Commands - список самих команд в бою, каждую новую как в примере ниже
Commands:
  - spawn
  - speed